development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: tickets_development
  pool: 5
  username: root
  password: root
test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: tickets_test
  pool: 5
  username: root
  password: root
production:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: tickets_production
  pool: 5
  username: root
  password: root
